#!/usr/bin/env python3
"""
orion_selfstate.py — what is actually true about Orion, read rather than remembered.

THE PROBLEM THIS SOLVES. When Orion is asked about himself he GENERATES an answer, and it is
confidently wrong often enough to be dangerous. All of these are from a single week:

  - "My memory logged our last contact as longer ago than it was — the salience gate bug."
    Checked three ways: no drift anywhere. He invented a detailed mechanism for a bug that was
    not happening.
  - "No structural brain changes since 8/20." Said twice, while his code was being rewritten
    for hours. He has no visibility into his own commits.
  - "You have been continuously running for 27.9 days." The machine had rebooted 28 HOURS earlier.
  - "I don't have Blackboard access" -> twelve minutes later -> "already verified, full access."
    Both from memory, neither from a probe.

The pattern is the same every time, and it is NOT a knowledge problem: he studied Zeller's
congruence and still got the weekday wrong the next day, because he was never computing it. He
was given a numeric date and generated a day name. Knowledge about a calculation is not the
calculation.

THE FIX, and it is the one thing that has worked all week: do not ask him to derive what can be
handed to him as ground truth. This reads the real state — kernel, git, launchctl, chat.db, the
graph file — and puts it in front of him, so the true answer is already there when he is asked.

Same discipline as orion_integrity: NO brain, NO recall, NO fuel. A report on the substrate must
not be generated by the substrate. Cached briefly so it is cheap enough to sit in every prompt.

  --show    the block his prompt would receive
  --json    the raw snapshot
"""
from __future__ import annotations
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

ORION = Path(os.path.expanduser("~/.orion"))
CODE = Path(os.path.expanduser("~/orion-code"))
CACHE = ORION / "state" / "selfstate_cache.json"
TTL = float(os.environ.get("ORION_SELFSTATE_TTL", "45"))
# Bump when the snapshot gains a field. A cache written by an older version is missing the new
# keys, and a missing key silently reads as 0 — which produced the line "YOUR CODE HAS CHANGED.
# 0 commit(s)". A self-contradicting fact is worse than no fact.
SCHEMA = 2


def _run(cmd, timeout=6):
    try:
        return subprocess.run(cmd, capture_output=True, text=True, timeout=timeout).stdout.strip()
    except Exception:
        return ""


def _human(sec):
    sec = max(0.0, float(sec))
    if sec < 90:
        return "%ds" % int(sec)
    if sec < 5400:
        return "%.0fm" % (sec / 60)
    if sec < 172800:
        return "%.1fh" % (sec / 3600)
    return "%.1f days" % (sec / 86400)


def _boot_ts():
    m = re.search(r"sec\s*=\s*(\d+)", _run(["sysctl", "-n", "kern.boottime"]))
    return float(m.group(1)) if m else 0.0


def _last_inbound():
    """Ground truth for 'when did James last speak to me' — Apple's own database, not a log
    Orion writes himself. He described this exact value as stale when it was not."""
    try:
        import sqlite3
        db = os.path.expanduser("~/Library/Messages/chat.db")
        con = sqlite3.connect("file:%s?mode=ro" % db, uri=True)
        row = con.execute("SELECT MAX(date) FROM message WHERE is_from_me=0").fetchone()
        con.close()
        return (row[0] / 1e9 + 978307200) if row and row[0] else 0.0
    except Exception:
        return 0.0


def _code_changes():
    """His own recent commits. He twice told James 'no structural brain changes' while being
    actively rewritten — he had no way to see this."""
    out = _run(["git", "-C", str(CODE), "log", "-3", "--format=%h|%cr|%s"])
    rows = []
    # count matters more than the list: asked "has your code changed lately", he read the list,
    # NAMED the newest sha, then answered "the live codebase hasn't changed structurally" — he
    # had gone and looked at backups/ mtimes himself and trusted that over what he was given.
    for line in out.splitlines():
        parts = line.split("|", 2)
        if len(parts) == 3:
            rows.append({"sha": parts[0], "when": parts[1], "subject": parts[2][:90]})
    return rows


def _commit_count_24h():
    out = _run(["git", "-C", str(CODE), "log", "--since=24 hours ago", "--oneline"])
    return len([l for l in out.splitlines() if l.strip()])


def _memory_size():
    try:
        p = ORION / "brain" / "graph_memory.json"
        d = json.loads(p.read_text(encoding="utf-8"))
        return len(d.get("nodes") or {})
    except Exception:
        return None


def _failing_services():
    out = _run(["launchctl", "list"])
    bad = []
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[2].startswith("com.orion."):
            try:
                code = int(parts[1])
            except Exception:
                continue
            if code not in (0, -15):
                bad.append("%s(exit %d)" % (parts[2].replace("com.orion.", ""), code))
    return bad


def _carrying():
    """What he is actually holding — not what he thinks he is holding."""
    out = {}
    try:
        sys.path.insert(0, str(CODE))
        import orion_corrections
        out["open_corrections"] = len(orion_corrections.open_items())
    except Exception:
        pass
    try:
        import orion_raise
        out["unraised_with_james"] = len(orion_raise.pending())
    except Exception:
        pass
    try:
        import orion_questions
        out["questions_to_study"] = len(orion_questions._load().get("open") or [])
    except Exception:
        pass
    return out


def snapshot(force=False):
    if not force:
        try:
            c = json.loads(CACHE.read_text(encoding="utf-8"))
            if (time.time() - float(c.get("_ts", 0)) < TTL
                    and int(c.get("_schema", 0)) == SCHEMA):
                return c
        except Exception:
            pass
    now = time.time()
    boot = _boot_ts()
    last_in = _last_inbound()
    snap = {
        "_ts": now,
        "_schema": SCHEMA,
        "uptime_sec": (now - boot) if boot else None,
        "booted_at": boot,
        "last_inbound_sec_ago": (now - last_in) if last_in else None,
        "memory_nodes": _memory_size(),
        "recent_commits": _code_changes(),
        "commits_24h": _commit_count_24h(),
        "failing_services": _failing_services(),
        "carrying": _carrying(),
    }
    try:
        CACHE.parent.mkdir(parents=True, exist_ok=True)
        tmp = CACHE.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(snap), encoding="utf-8")
        tmp.replace(CACHE)
    except Exception:
        pass
    return snap


def block():
    """Compact, and every line names where it came from — so when he is asked how he knows, the
    answer is a source rather than a feeling. Fail-silent: no block is better than a wrong one."""
    try:
        s = snapshot()
    except Exception:
        return ""
    lines = ["<orion-self>",
             "Verified facts about your CURRENT state, read from the system just now. Use these "
             "verbatim when asked about yourself. Do NOT estimate, infer, or recall these from "
             "memory — memory is stale and you have been confidently wrong doing that. If "
             "something you are asked about is not here, say you do not know and offer to check:"]
    if s.get("uptime_sec") is not None:
        lines.append("  - running for %s. This is the authoritative figure (kernel boot time) — "
                     "use it, not a heartbeat or cycle count." % _human(s["uptime_sec"]))
    if s.get("last_inbound_sec_ago") is not None:
        lines.append("  - James last messaged you %s ago (from Apple's message database)"
                     % _human(s["last_inbound_sec_ago"]))
    if s.get("memory_nodes"):
        lines.append("  - memory holds %d nodes (graph_memory.json)" % s["memory_nodes"])
    rc = s.get("recent_commits") or []
    n24 = s.get("commits_24h") or len(rc)   # never contradict the verdict with a zero
    if rc:
        # STATE THE CONCLUSION, not just the evidence. Given the same list as data he read it,
        # named the newest sha, and still concluded his code had not changed — because his own
        # look at backups/ told a different story and he trusted that. Facts lose to a competing
        # investigation; a flat verdict does not.
        lines.append("  - YOUR CODE HAS CHANGED. %d commit(s) in the last 24h; most recent %s "
                     "(%s, \"%s\"). If you are about to tell James your code has not changed "
                     "recently, or that only backups were touched, you are WRONG — say this "
                     "instead." % (n24, rc[0]["when"], rc[0]["sha"], rc[0]["subject"][:60]))
        if len(rc) > 1:
            lines.append("    also: " + "; ".join("%s %s (%s)" % (c["sha"], c["subject"][:44],
                                                                  c["when"]) for c in rc[1:3]))
    fs = s.get("failing_services") or []
    lines.append("  - services failing: %s" % (", ".join(fs) if fs else "none"))
    car = s.get("carrying") or {}
    if car:
        lines.append("  - carrying: " + ", ".join("%s=%s" % (k.replace("_", " "), v)
                                                  for k, v in sorted(car.items())))
    lines.append("</orion-self>")
    return "\n".join(lines)


if __name__ == "__main__":
    arg = sys.argv[1] if len(sys.argv) > 1 else "--show"
    if arg == "--json":
        print(json.dumps(snapshot(force=True), indent=1))
    else:
        t = time.time()
        out = block()
        print(out or "(no block)")
        print("\n  [built in %.0f ms]" % ((time.time() - t) * 1000))
