#!/usr/bin/env python3
"""
ORION CONFIG — User-specific settings loaded by setup wizard.
This file is generated by setup.py and should NOT be committed to git.
Add orion_config.py to .gitignore after setup.
"""
import os
import json

CONFIG_PATH = os.path.join(os.path.dirname(__file__), "orion_user_config.json")

DEFAULT_CONFIG = {
    "tier": "personal",  # personal, developer, arsenal
    "portable": False,
    "data_dir": os.path.expanduser("~/.orion"),
    "brain_port": 5555,

    # Devices (developer/arsenal tiers only)
    "devices": {},
    # Example:
    # "devices": {
    #     "server": {"ip": "192.168.1.100", "user": "admin", "role": "Central hub"},
    #     "workstation": {"ip": "192.168.1.101", "user": "user", "role": "GPU inference"},
    # }

    # Fuel sources (auto-detected by setup wizard)
    "fuel": {
        "claude_cli": False,
        "ollama_local": False,
        "ollama_remote": [],
        "chatgpt": False,
        "gemini": False,
        "codex": False,
        "tgpt": False,
    },

    # Email (optional)
    "email": {
        "enabled": False,
        "tool_path": "",
        "address": "",
    },

    # Paths
    "tools": {
        "himalaya": "",
        "security_dir": "",
        "agents_dir": "",
    },
}


def load_config():
    """Load user config. Returns defaults if no config file exists."""
    if os.path.exists(CONFIG_PATH):
        with open(CONFIG_PATH, "r") as f:
            user = json.load(f)
            merged = {**DEFAULT_CONFIG, **user}
            return merged
    return DEFAULT_CONFIG.copy()


def save_config(config):
    """Save config to disk."""
    with open(CONFIG_PATH, "w") as f:
        json.dump(config, f, indent=2)


def get_devices(config):
    """Return device list from config."""
    return config.get("devices", {})


def get_fuel_sources(config):
    """Return enabled fuel sources."""
    fuel = config.get("fuel", {})
    return {k: v for k, v in fuel.items() if v}


CONFIG = load_config()
